name: Build cosmosc2

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: website
      - name: Checkout COSMOS
        uses: actions/checkout@v2
        with:
          repository: BallAerospace/COSMOS
          ref: master
          path: COSMOS/cosmos
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Install dependencies
        working-directory: website
        run: bundle install
      - name: Run build
        working-directory: website
        run: bundle exec rake build
      - name: Git commit
        working-directory: website
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add _site/*
          git commit -m "Built site"
          git push
      - name: Run deploy
        working-directory: website
        run: bundle exec rake deploy
